### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ihachani** [gudwin/botbuilder-unit#4]
The License for this project is GPL which means any project that uses this should be GPL (Copyleft). Is this intended? 
I suggest using LGPL which allows using the code without forcing the user to make their code public and make sure that any updates to the botbuilder-unit itself is published under LGPL.

**Comment by gudwin** [comment]
Agree. Switched to LGPL and released 0.6.5 version

https://github.com/gudwin/botbuilder-unit/releases/tag/0.6.5
